"""Small, dependency-free helpers for public intelligence release manifests."""

import hashlib
import json
import re
import unicodedata


PUBLIC_INTELLIGENCE_QUALITY_GATE_VERSION = "2026-09-22-v3"
PUBLIC_INTELLIGENCE_SITEMAP_BATCH_SIZE = 5_000
PUBLIC_COMPANY_MIN_OBSERVED_VALUE = 10_000
PUBLIC_HEALTHCARE_DOMINANCE_SHARE = 0.8
PUBLIC_AWARD_MIN_OBSERVED_VALUE = 1_000_000
PUBLIC_AWARD_MIN_ACTIONS = 2
PUBLIC_AWARD_MIN_DESCRIPTION_LENGTH = 30
PUBLIC_SOLICITATION_MIN_TITLE_LENGTH = 12
PUBLIC_SOLICITATION_MIN_DESCRIPTION_LENGTH = 150
PUBLIC_SOLICITATION_MIN_METADATA_FIELDS = 1
PUBLIC_NSN_MIN_OBSERVED_VALUE = 100
PUBLIC_NSN_UNMAPPED_MIN_OBSERVED_VALUE = 1_000
PUBLIC_NSN_MIN_CONTEXT_COUNT = 2


def public_entity_slug(value: str) -> str:
    """Match the canonical entity slug generated by the public Next.js routes."""
    ascii_value = (
        unicodedata.normalize("NFKD", str(value or ""))
        .encode("ascii", "ignore")
        .decode("ascii")
        .lower()
        .replace("&", " and ")
    )
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_value).strip("-")[:90]
    return slug or "defense-company"


def public_content_fingerprint(*values) -> str:
    """Return a stable digest for the source fields that materially shape a page."""
    encoded = json.dumps(values, default=str, ensure_ascii=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def previous_publication_entries(conn) -> dict:
    """Load just enough of the previous manifest to preserve truthful lastmod dates."""
    try:
        columns = {
            str(row[0]).strip().lower()
            for row in conn.execute("DESCRIBE public_intelligence_manifest").fetchall()
        }
        if not {"entity_type", "entity_id", "content_fingerprint", "last_modified"}.issubset(columns):
            return {}
        rows = conn.execute("""
            SELECT entity_type, entity_id, content_fingerprint, last_modified
            FROM public_intelligence_manifest
        """).fetchall()
        return {
            f"{entity_type}:{entity_id}": {
                "content_fingerprint": str(content_fingerprint or ""),
                "last_modified": str(last_modified or ""),
            }
            for entity_type, entity_id, content_fingerprint, last_modified in rows
        }
    except Exception:
        return {}
