"""Small, dependency-free helpers for public intelligence release manifests."""

import hashlib
import json
import re
import unicodedata


PUBLIC_INTELLIGENCE_QUALITY_GATE_VERSION = "2026-09-22-v3"
PUBLIC_INTELLIGENCE_SITEMAP_BATCH_SIZE = 5_000
PUBLIC_COMPANY_MIN_OBSERVED_VALUE = 10_000
PUBLIC_HEALTHCARE_DOMINANCE_SHARE = 0.8
PUBLIC_AWARD_MIN_OBSERVED_VALUE = 1_000_000
PUBLIC_AWARD_MIN_ACTIONS = 2
PUBLIC_AWARD_MIN_DESCRIPTION_LENGTH = 30
PUBLIC_SOLICITATION_MIN_TITLE_LENGTH = 12
PUBLIC_SOLICITATION_MIN_DESCRIPTION_LENGTH = 150
PUBLIC_SOLICITATION_MIN_METADATA_FIELDS = 1
PUBLIC_NSN_MIN_OBSERVED_VALUE = 100
PUBLIC_NSN_UNMAPPED_MIN_OBSERVED_VALUE = 1_000
PUBLIC_NSN_MIN_CONTEXT_COUNT = 2

PUBLIC_INTELLIGENCE_MANIFEST_COLUMNS = (
    "entity_type",
    "entity_id",
    "canonical_path",
    "display_name",
    "richness_score",
    "decision_reasons",
    "last_modified",
    "release_id",
    "schema_version",
    "content_fingerprint",
    "quality_gate_version",
)


def public_entity_slug(value: str) -> str:
    """Match the canonical entity slug generated by the public Next.js routes."""
    ascii_value = (
        unicodedata.normalize("NFKD", str(value or ""))
        .encode("ascii", "ignore")
        .decode("ascii")
        .lower()
        .replace("&", " and ")
    )
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_value).strip("-")[:90]
    return slug or "defense-company"


def public_content_fingerprint(*values) -> str:
    """Return a stable digest for the source fields that materially shape a page."""
    encoded = json.dumps(values, default=str, ensure_ascii=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def append_active_opportunity_nsn_candidates(
    conn,
    *,
    remaining_slots: int,
    generated_date: str,
    release_id: str,
    schema_version: int,
    quality_gate_version: str,
) -> dict:
    """Add valid opportunity-only NSNs without displacing procurement candidates.

    The primary NSN quality gate is intentionally procurement-history based.  An
    active solicitation is independently useful public information, however, and
    may exist before an NSN has any observed award history.  Append those records
    only after the normal ranked cohort has been selected so an opportunity cannot
    evict a previously eligible page.
    """
    slots = max(0, int(remaining_slots))
    required_candidate_columns = {
        "entity_type", "entity_id", "canonical_path", "display_name",
        "richness_score", "decision_reasons", "last_modified", "release_id",
        "schema_version", "content_fingerprint", "quality_gate_version",
        "quality_gate_matches",
    }
    if slots == 0 or not required_candidate_columns.issubset(
        _table_columns(conn, "public_nsn_manifest_candidates_next")
    ):
        return {"added": 0, "quality_gate_matches": 0}
    if not {
        "niin", "active_solicitation_count", "nsn",
    }.issubset(_table_columns(conn, "v_nsn_opportunity_summary")):
        return {"added": 0, "quality_gate_matches": 0}
    if not {"niin", "nsn", "item_name", "fsc_code"}.issubset(
        _table_columns(conn, "v_nsn_profile_lookup")
    ):
        return {"added": 0, "quality_gate_matches": 0}

    escaped_date = str(generated_date).replace("'", "''")
    escaped_release = str(release_id).replace("'", "''")
    escaped_quality_gate = str(quality_gate_version).replace("'", "''")
    existing_quality_matches = int(conn.execute("""
        SELECT COALESCE(MAX(quality_gate_matches), 0)
        FROM public_nsn_manifest_candidates_next
    """).fetchone()[0])

    conn.execute("DROP TABLE IF EXISTS public_nsn_opportunity_manifest_additions")
    conn.execute(f"""
        CREATE TABLE public_nsn_opportunity_manifest_additions AS
        WITH profile AS (
            SELECT
                LPAD(TRIM(CAST(niin AS VARCHAR)), 9, '0') AS niin,
                MAX(NULLIF(REGEXP_REPLACE(CAST(nsn AS VARCHAR), '[^0-9]', '', 'g'), '')) AS nsn,
                MAX(NULLIF(TRIM(CAST(item_name AS VARCHAR)), '')) AS item_name,
                MAX(NULLIF(TRIM(CAST(fsc_code AS VARCHAR)), '')) AS fsc_code
            FROM v_nsn_profile_lookup
            WHERE niin IS NOT NULL
            GROUP BY 1
        ), active AS (
            SELECT
                LPAD(TRIM(CAST(opportunity.niin AS VARCHAR)), 9, '0') AS niin,
                MAX(NULLIF(REGEXP_REPLACE(CAST(opportunity.nsn AS VARCHAR), '[^0-9]', '', 'g'), '')) AS opportunity_nsn,
                MAX(COALESCE(TRY_CAST(active_solicitation_count AS INTEGER), 0)) AS active_solicitation_count,
                MAX(TRY_CAST(next_response_deadline AS TIMESTAMP)) AS next_response_deadline,
                MAX(NULLIF(TRIM(CAST(next_solicitation_number AS VARCHAR)), '')) AS next_solicitation_number,
                MAX(TRY_CAST(next_quantity AS DOUBLE)) AS next_quantity
            FROM v_nsn_opportunity_summary opportunity
            WHERE COALESCE(TRY_CAST(active_solicitation_count AS INTEGER), 0) > 0
              AND opportunity.niin IS NOT NULL
            GROUP BY 1
        ), canonical AS (
            SELECT
                active.*,
                profile.item_name,
                profile.fsc_code,
                CASE
                    WHEN LENGTH(active.opportunity_nsn) = 13 THEN active.opportunity_nsn
                    WHEN LENGTH(profile.nsn) = 13 THEN profile.nsn
                    WHEN LENGTH(REGEXP_REPLACE(COALESCE(profile.fsc_code, ''), '[^0-9]', '', 'g')) = 4
                    THEN REGEXP_REPLACE(profile.fsc_code, '[^0-9]', '', 'g') || active.niin
                    ELSE active.niin
                END AS canonical_entity_id
            FROM active
            INNER JOIN profile USING (niin)
            WHERE NULLIF(TRIM(CAST(profile.item_name AS VARCHAR)), '') IS NOT NULL
              AND UPPER(TRIM(CAST(profile.item_name AS VARCHAR))) NOT IN ('NAN', 'NONE', 'NULL')
              AND UPPER(TRIM(COALESCE(profile.fsc_code, ''))) NOT LIKE '65%'
        ), eligible AS (
            SELECT canonical.*
            FROM canonical
            LEFT JOIN public_nsn_manifest_candidates_next existing
              ON existing.entity_type = 'nsn'
             AND (
                    existing.entity_id = canonical.canonical_entity_id
                 OR RIGHT(REGEXP_REPLACE(existing.entity_id, '[^0-9]', '', 'g'), 9) = canonical.niin
             )
            WHERE existing.entity_id IS NULL
              AND LENGTH(canonical.canonical_entity_id) IN (9, 13)
        )
        SELECT
            'nsn' AS entity_type,
            canonical_entity_id AS entity_id,
            '/intelligence/nsn/' || canonical_entity_id AS canonical_path,
            item_name AS display_name,
            ROUND(20 + LEAST(active_solicitation_count, 10) * 2, 4) AS richness_score,
            'active-solicitation' AS decision_reasons,
            '{escaped_date}' AS last_modified,
            '{escaped_release}' AS release_id,
            {int(schema_version)} AS schema_version,
            SHA256(CONCAT_WS(
                '|', canonical_entity_id, niin, item_name,
                CAST(active_solicitation_count AS VARCHAR),
                CAST(next_response_deadline AS VARCHAR),
                next_solicitation_number, CAST(next_quantity AS VARCHAR)
            )) AS content_fingerprint,
            '{escaped_quality_gate}' AS quality_gate_version,
            0::BIGINT AS quality_gate_matches
        FROM eligible
        ORDER BY next_response_deadline, canonical_entity_id
        LIMIT ?
    """, [slots])
    added = int(conn.execute(
        "SELECT COUNT(*) FROM public_nsn_opportunity_manifest_additions"
    ).fetchone()[0])
    if added:
        quality_matches = existing_quality_matches + added
        conn.execute(
            "UPDATE public_nsn_manifest_candidates_next SET quality_gate_matches = ?",
            [quality_matches],
        )
        conn.execute(
            "UPDATE public_nsn_opportunity_manifest_additions SET quality_gate_matches = ?",
            [quality_matches],
        )
        conn.execute("""
            INSERT INTO public_nsn_manifest_candidates_next
            SELECT * FROM public_nsn_opportunity_manifest_additions
        """)
    else:
        quality_matches = existing_quality_matches
    conn.execute("DROP TABLE public_nsn_opportunity_manifest_additions")
    return {"added": added, "quality_gate_matches": quality_matches}


def previous_publication_entries(conn) -> dict:
    """Load just enough of the previous manifest to preserve truthful lastmod dates."""
    try:
        columns = {
            str(row[0]).strip().lower()
            for row in conn.execute("DESCRIBE public_intelligence_manifest").fetchall()
        }
        if not {"entity_type", "entity_id", "content_fingerprint", "last_modified"}.issubset(columns):
            return {}
        rows = conn.execute("""
            SELECT entity_type, entity_id, content_fingerprint, last_modified
            FROM public_intelligence_manifest
        """).fetchall()
        return {
            f"{entity_type}:{entity_id}": {
                "content_fingerprint": str(content_fingerprint or ""),
                "last_modified": str(last_modified or ""),
            }
            for entity_type, entity_id, content_fingerprint, last_modified in rows
        }
    except Exception:
        return {}


def _table_columns(conn, table_name: str) -> set[str]:
    """Return normalised columns for a trusted, internally named DuckDB table."""
    try:
        return {
            str(row[0]).strip().lower()
            for row in conn.execute(f"DESCRIBE {table_name}").fetchall()
        }
    except Exception:
        return set()


def stage_public_intelligence_manifest(
    conn,
    *,
    release_id: str,
    generated_date: str,
    sitemap_batch_size: int = PUBLIC_INTELLIGENCE_SITEMAP_BATCH_SIZE,
) -> dict:
    """Stage a release manifest without silently evicting published entities.

    ``public_intelligence_manifest_candidates_next`` contains the entities that
    were refreshed and passed today's quality checks.  The active manifest is
    the last-known-good publication set.  A missing candidate is therefore not
    a deletion instruction: prior rows remain published until a separate,
    deliberate removal policy is introduced.
    """
    required = set(PUBLIC_INTELLIGENCE_MANIFEST_COLUMNS)
    candidate_columns = _table_columns(
        conn, "public_intelligence_manifest_candidates_next"
    )
    missing_candidate_columns = required - candidate_columns
    if missing_candidate_columns:
        raise RuntimeError(
            "Candidate public manifest is missing required columns: "
            + ", ".join(sorted(missing_candidate_columns))
        )

    previous_columns = _table_columns(conn, "public_intelligence_manifest")
    has_previous_manifest = required.issubset(previous_columns)
    escaped_release_id = str(release_id).replace("'", "''")
    escaped_generated_date = str(generated_date).replace("'", "''")
    safe_batch_size = max(1, int(sitemap_batch_size))

    conn.execute("DROP TABLE IF EXISTS public_intelligence_manifest_next")
    if has_previous_manifest:
        conn.execute(f"""
            CREATE TABLE public_intelligence_manifest_next AS
            WITH merged AS (
                SELECT
                    candidate.entity_type,
                    candidate.entity_id,
                    candidate.canonical_path,
                    candidate.display_name,
                    candidate.richness_score,
                    candidate.decision_reasons,
                    CASE
                        WHEN previous.content_fingerprint = candidate.content_fingerprint
                         AND REGEXP_FULL_MATCH(
                             COALESCE(previous.last_modified, ''),
                             '\\d{{4}}-\\d{{2}}-\\d{{2}}'
                         )
                        THEN previous.last_modified
                        ELSE '{escaped_generated_date}'
                    END AS last_modified,
                    '{escaped_release_id}' AS release_id,
                    candidate.schema_version,
                    candidate.content_fingerprint,
                    candidate.quality_gate_version
                FROM public_intelligence_manifest_candidates_next candidate
                LEFT JOIN public_intelligence_manifest previous
                  ON previous.entity_type = candidate.entity_type
                 AND previous.entity_id = candidate.entity_id

                UNION ALL

                SELECT
                    previous.entity_type,
                    previous.entity_id,
                    previous.canonical_path,
                    previous.display_name,
                    previous.richness_score,
                    previous.decision_reasons,
                    previous.last_modified,
                    '{escaped_release_id}' AS release_id,
                    previous.schema_version,
                    previous.content_fingerprint,
                    previous.quality_gate_version
                FROM public_intelligence_manifest previous
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM public_intelligence_manifest_candidates_next candidate
                    WHERE candidate.entity_type = previous.entity_type
                      AND candidate.entity_id = previous.entity_id
                )
            )
            SELECT
                merged.*,
                CAST(
                    FLOOR(
                        (ROW_NUMBER() OVER (
                            PARTITION BY entity_type
                            ORDER BY entity_id
                        ) - 1) / {safe_batch_size}
                    ) + 1 AS INTEGER
                ) AS sitemap_batch
            FROM merged
        """)
    else:
        conn.execute(f"""
            CREATE TABLE public_intelligence_manifest_next AS
            SELECT
                candidate.entity_type,
                candidate.entity_id,
                candidate.canonical_path,
                candidate.display_name,
                candidate.richness_score,
                candidate.decision_reasons,
                '{escaped_generated_date}' AS last_modified,
                '{escaped_release_id}' AS release_id,
                candidate.schema_version,
                candidate.content_fingerprint,
                candidate.quality_gate_version,
                CAST(
                    FLOOR(
                        (ROW_NUMBER() OVER (
                            PARTITION BY entity_type
                            ORDER BY entity_id
                        ) - 1) / {safe_batch_size}
                    ) + 1 AS INTEGER
                ) AS sitemap_batch
            FROM public_intelligence_manifest_candidates_next candidate
        """)

    retained_count = 0
    previous_count = 0
    if has_previous_manifest:
        previous_count = int(
            conn.execute("SELECT COUNT(*) FROM public_intelligence_manifest").fetchone()[0]
        )
        retained_count = int(conn.execute("""
            SELECT COUNT(*)
            FROM public_intelligence_manifest previous
            WHERE NOT EXISTS (
                SELECT 1
                FROM public_intelligence_manifest_candidates_next candidate
                WHERE candidate.entity_type = previous.entity_type
                  AND candidate.entity_id = previous.entity_id
            )
        """).fetchone()[0])
        missing_after_merge = int(conn.execute("""
            SELECT COUNT(*)
            FROM public_intelligence_manifest previous
            WHERE NOT EXISTS (
                SELECT 1
                FROM public_intelligence_manifest_next staged
                WHERE staged.entity_type = previous.entity_type
                  AND staged.entity_id = previous.entity_id
            )
        """).fetchone()[0])
        if missing_after_merge:
            conn.execute("DROP TABLE public_intelligence_manifest_next")
            raise RuntimeError(
                f"Public release safety invariant failed: {missing_after_merge} "
                "previously published entities would be removed"
            )

    staged_count = int(
        conn.execute("SELECT COUNT(*) FROM public_intelligence_manifest_next").fetchone()[0]
    )
    duplicate_count = int(conn.execute("""
        SELECT COALESCE(SUM(row_count - 1), 0)
        FROM (
            SELECT COUNT(*) AS row_count
            FROM public_intelligence_manifest_next
            GROUP BY entity_type, entity_id
            HAVING COUNT(*) > 1
        ) duplicates
    """).fetchone()[0])
    if duplicate_count:
        duplicate_keys = conn.execute("""
            SELECT entity_type, entity_id, COUNT(*) AS row_count
            FROM public_intelligence_manifest_next
            GROUP BY entity_type, entity_id
            HAVING COUNT(*) > 1
            ORDER BY row_count DESC, entity_type, entity_id
            LIMIT 10
        """).fetchall()
        conn.execute("DROP TABLE public_intelligence_manifest_next")
        raise RuntimeError(
            f"Public release safety invariant failed: {duplicate_count} duplicate "
            f"entity keys were staged: {duplicate_keys}"
        )
    if staged_count < previous_count:
        conn.execute("DROP TABLE public_intelligence_manifest_next")
        raise RuntimeError(
            "Public release safety invariant failed: staged manifest is smaller "
            "than the active manifest"
        )
    return {
        "previous_count": previous_count,
        "staged_count": staged_count,
        "retained_without_refresh": retained_count,
        "duplicate_count": duplicate_count,
    }


def preserve_projection_for_unrefreshed_entities(
    conn,
    *,
    next_table: str,
    active_table: str,
    entity_type: str,
    entity_column: str,
) -> int:
    """Keep an entity's active projection when it was not refreshed today.

    Table and column names are internal constants supplied by the caller.  The
    function intentionally works at entity granularity: a retained entity gets
    its complete prior projection, not a mixture of partial new and old rows.
    """
    safe_entity_type = str(entity_type).replace("'", "''")
    retained_count = int(conn.execute(f"""
        SELECT COUNT(*)
        FROM public_intelligence_manifest_next staged
        WHERE staged.entity_type = '{safe_entity_type}'
          AND NOT EXISTS (
              SELECT 1
              FROM public_intelligence_manifest_candidates_next candidate
              WHERE candidate.entity_type = staged.entity_type
                AND candidate.entity_id = staged.entity_id
          )
    """).fetchone()[0])
    if not retained_count:
        return 0

    next_columns = _table_columns(conn, next_table)
    active_columns = _table_columns(conn, active_table)
    if not next_columns or next_columns != active_columns:
        raise RuntimeError(
            f"Cannot retain {retained_count} {safe_entity_type} projections: "
            f"{active_table} and {next_table} schemas do not match"
        )

    conn.execute(f"""
        DELETE FROM {next_table} next_projection
        WHERE EXISTS (
            SELECT 1
            FROM public_intelligence_manifest_next staged
            WHERE staged.entity_type = '{safe_entity_type}'
              AND staged.entity_id = CAST(next_projection.{entity_column} AS VARCHAR)
              AND NOT EXISTS (
                  SELECT 1
                  FROM public_intelligence_manifest_candidates_next candidate
                  WHERE candidate.entity_type = staged.entity_type
                    AND candidate.entity_id = staged.entity_id
              )
        )
    """)
    conn.execute(f"""
        INSERT INTO {next_table}
        SELECT active_projection.*
        FROM {active_table} active_projection
        INNER JOIN public_intelligence_manifest_next staged
          ON staged.entity_type = '{safe_entity_type}'
         AND staged.entity_id = CAST(active_projection.{entity_column} AS VARCHAR)
        WHERE NOT EXISTS (
            SELECT 1
            FROM public_intelligence_manifest_candidates_next candidate
            WHERE candidate.entity_type = staged.entity_type
              AND candidate.entity_id = staged.entity_id
        )
    """)
    return retained_count


def last_known_good_public_release(previous_release):
    """Return an isolated copy suitable for reuse after a failed refresh."""
    if not previous_release:
        return None
    return json.loads(json.dumps(previous_release))
