"""Machine-readable registry for the first trusted Ask Mimir metric primitives."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Dict, Iterable, List


CALCULATION_VERSION = "mimir-derived-2026-08-v3"


@dataclass(frozen=True)
class MetricDefinition:
    metric_id: str
    name: str
    definition: str
    formula: str
    unit: str
    value_status: str
    release_status: str
    source_grain: str
    evidence_basis: str


METRICS: Dict[str, MetricDefinition] = {
    "T01": MetricDefinition(
        "T01",
        "Net observed value",
        "Signed value for one explicitly declared financial measure, scope and fiscal year.",
        "sum(signed action value)",
        "USD",
        "observed",
        "phase_1",
        "action",
        "award_key and transaction_key",
    ),
    "T02": MetricDefinition(
        "T02",
        "Net value change",
        "Current completed-fiscal-year net value less the comparison year for the declared measure.",
        "current T01 - prior T01",
        "USD",
        "derived",
        "phase_1",
        "fiscal-year action rollup",
        "both period components and their action keys",
    ),
    "T03": MetricDefinition(
        "T03",
        "Year-on-year growth",
        "Net value change divided by the prior completed-fiscal-year value for the declared measure. Null when the prior denominator is non-positive.",
        "(current T01 - prior T01) / prior T01",
        "percent",
        "derived",
        "phase_1",
        "fiscal-year action rollup",
        "both period components and their action keys",
    ),
    "T04": MetricDefinition(
        "T04",
        "Three-year CAGR",
        "Compound annual growth between fiscal-year endpoints exactly three years apart.",
        "((current T01 / T01 three FYs earlier) ** (1/3) - 1)",
        "percent",
        "derived",
        "phase_1",
        "fiscal-year action rollup",
        "four annual observations and their action keys",
    ),
    "T06": MetricDefinition(
        "T06",
        "Growth acceleration",
        "Current year-on-year growth less the preceding year-on-year growth.",
        "current T03 - prior T03",
        "percentage_points",
        "derived",
        "phase_1",
        "fiscal-year action rollup",
        "three fiscal-year components and their action keys",
    ),
    "T09": MetricDefinition(
        "T09",
        "Positive and de-obligation mix",
        "Positive action value, negative action value and net value shown separately.",
        "positive sum; negative sum; signed total",
        "USD",
        "observed",
        "phase_1",
        "action",
        "positive and negative transaction keys",
    ),
    "T10": MetricDefinition(
        "T10",
        "Distinct award activity",
        "Distinct authoritative award keys with activity in the declared fiscal year.",
        "count(distinct award_key)",
        "count",
        "observed",
        "phase_1",
        "award",
        "award_key list and supporting transaction keys",
    ),
    "T12": MetricDefinition(
        "T12",
        "Contract-action activity",
        "Distinct authoritative transaction keys in the declared fiscal year.",
        "count(distinct transaction_key)",
        "count",
        "observed",
        "phase_1",
        "action",
        "transaction_key list",
    ),
    "T14": MetricDefinition(
        "T14",
        "Activity recency",
        "Days from the latest authoritative action to the metric as-of date.",
        "as_of_date - max(action_date)",
        "days",
        "derived",
        "phase_1",
        "action",
        "latest transaction key",
    ),
    "C01": MetricDefinition(
        "C01",
        "Observed share",
        "Scope net value divided by same-period net value for the declared measure in the explicitly named peer universe.",
        "scope T01 / peer-universe T01",
        "percent",
        "derived",
        "phase_1",
        "fiscal-year action rollup",
        "numerator and full denominator composition",
    ),
    "C02": MetricDefinition(
        "C02",
        "Observed share change",
        "Current observed share less comparison-year observed share.",
        "current C01 - prior C01",
        "percentage_points",
        "derived",
        "phase_1",
        "fiscal-year action rollup",
        "both peer universes and numerator records",
    ),
    "C03": MetricDefinition(
        "C03",
        "Peer rank",
        "Rank by the declared signed measure within an explicit peer universe, with deterministic ties.",
        "dense rank by value descending, stable entity ID ascending",
        "rank",
        "derived",
        "phase_1",
        "fiscal-year action rollup",
        "full peer table and underlying actions",
    ),
    "C04": MetricDefinition(
        "C04",
        "Peer rank change",
        "Prior rank less current rank; positive values indicate improvement.",
        "prior C03 - current C03",
        "rank_positions",
        "derived",
        "phase_1",
        "fiscal-year action rollup",
        "both complete peer tables",
    ),
    "C09": MetricDefinition(
        "C09",
        "Competed positive-obligation rate",
        "Positive USAspending obligation value classified as competed divided by classified positive obligation value in the declared scope and period.",
        "competed positive obligations / classified positive obligations",
        "percent",
        "derived",
        "phase_1_competition",
        "classified USAspending award actions",
        "included competition codes, unclassified coverage, award keys and transaction keys",
    ),
    "C10": MetricDefinition(
        "C10",
        "Offers intensity",
        "Median and mean offers received for the declared award population, with missingness reported separately.",
        "median and mean offers_received by distinct award",
        "bundle",
        "derived",
        "phase_1_competition",
        "classified USAspending awards",
        "award list, offers field, competition type and missingness",
    ),
    "C11": MetricDefinition(
        "C11",
        "Observed sole or single-source position",
        "Positive USAspending obligation value and award count whose authoritative competition classification indicates sole or single source.",
        "sole-or-single-source positive value and awards / classified population",
        "bundle",
        "derived",
        "phase_1_competition",
        "classified USAspending award actions",
        "classification code and label, award list, actions and unclassified coverage",
    ),
    "C15": MetricDefinition(
        "C15",
        "Positive-value share",
        "Scope positive value divided by positive value for the declared measure in the explicit peer universe.",
        "scope positive value / peer-universe positive value",
        "percent",
        "derived",
        "phase_1",
        "positive action",
        "positive numerator and denominator actions; excluded negative actions",
    ),
    "C16": MetricDefinition(
        "C16",
        "Positive-value share change",
        "Current positive-value share less comparison-year positive-value share for the declared measure.",
        "current C15 - prior C15",
        "percentage_points",
        "derived",
        "phase_1",
        "positive action",
        "both positive-value peer tables and excluded negatives",
    ),
    "E03": MetricDefinition(
        "E03",
        "Customer concentration",
        "HHI, leading-customer shares and effective customer count using positive action value by contracting sub-agency.",
        "concentration(positive value by sub_agency)",
        "bundle",
        "derived",
        "phase_1",
        "positive action",
        "customer component table and transaction keys",
    ),
    "E04": MetricDefinition(
        "E04",
        "Platform concentration",
        "HHI, leading-platform shares and effective platform count using positive attributed value.",
        "concentration(positive attributed value by platform)",
        "bundle",
        "derived",
        "phase_1",
        "positive attributed action",
        "platform components, mapping status and transaction keys",
    ),
    "E06": MetricDefinition(
        "E06",
        "Recipient-site concentration on platform",
        "HHI, leading-recipient shares and effective recipient count using the positive declared measure attributed to a platform. Prime-obligation recipients are not a tier-one supplier map.",
        "concentration(positive attributed value by recipient CAGE site)",
        "bundle",
        "derived",
        "phase_1",
        "positive attributed action",
        "recipient components, mapping status and transaction keys",
    ),
    "E13": MetricDefinition(
        "E13",
        "Platform mapping coverage",
        "Attributed, shared-use and unmapped action value and record coverage, kept separate.",
        "coverage by platform_attribution_status",
        "bundle",
        "derived",
        "phase_1",
        "action",
        "mapping-status components and transaction keys",
    ),
    "E14": MetricDefinition(
        "E14",
        "Entity-resolution coverage",
        "Action value and records with a resolved CAGE versus records without one.",
        "coverage by normalized vendor_cage presence",
        "bundle",
        "derived",
        "phase_1",
        "action",
        "resolved and unresolved action lists",
    ),
    "S01": MetricDefinition(
        "S01",
        "Observed subcontract value",
        "Modelled value from selected, deduplicated subcontract reports for the declared period, kept separate from prime obligations.",
        "sum(subaward_value)",
        "USD",
        "modelled",
        "phase_1_subaward",
        "selected subaward report",
        "source_report_id, source_dedup_key and prime award key",
    ),
    "S03": MetricDefinition(
        "S03",
        "Active subcontract relationship count",
        "Distinct observed prime-parent to subcontractor-parent relationships in the declared period.",
        "count(distinct prime_parent, sub_parent)",
        "count",
        "observed",
        "phase_1_subaward",
        "selected subaward report",
        "relationship list and source report IDs",
    ),
    "I01": MetricDefinition(
        "I01",
        "NIIN observed procurement-value growth",
        "Change in DLA extended procurement value by NIIN across completed fiscal years.",
        "growth(sum(quantity * unit price) by NIIN and FY)",
        "percent",
        "derived",
        "phase_1_item",
        "DLA procurement line",
        "DLA transaction keys",
    ),
    "I05": MetricDefinition(
        "I05",
        "Observed NIIN supplier share",
        "Supplier positive DLA procurement value divided by positive observed value for the same NIIN and fiscal window.",
        "supplier positive DLA value / NIIN positive DLA value",
        "percent",
        "derived",
        "phase_1_item",
        "DLA procurement line",
        "supplier numerator and NIIN denominator transaction keys",
    ),
    "I06": MetricDefinition(
        "I06",
        "Observed NIIN supplier concentration",
        "HHI and leading shares across suppliers with positive observed DLA procurement value.",
        "concentration(positive DLA value by CAGE)",
        "bundle",
        "derived",
        "phase_1_item",
        "DLA procurement line",
        "supplier components and DLA transaction keys",
    ),
    "I10": MetricDefinition(
        "I10",
        "Observed single-supplier flag",
        "Exactly one supplier has positive observed DLA procurement activity in the declared lookback.",
        "count(distinct observed supplier CAGE) = 1",
        "boolean",
        "derived",
        "phase_1_item",
        "DLA procurement line",
        "observed supplier list and transaction keys",
    ),
    "I12": MetricDefinition(
        "I12",
        "NIIN procurement recency",
        "Days since the latest observed DLA procurement line for the NIIN or NIIN-supplier relationship.",
        "as_of_date - max(DLA action_date)",
        "days",
        "derived",
        "phase_1_item",
        "DLA procurement line",
        "latest DLA transaction key",
    ),
    "I13": MetricDefinition(
        "I13",
        "Cross-platform item commonality",
        "Number and list of distinct mapped platforms associated with a NIIN; this is a reference association, not financial allocation.",
        "count(distinct platform-NIIN association)",
        "count_and_list",
        "derived",
        "phase_1_item",
        "platform-NIIN mapping row",
        "NIIN-platform bridge rows and mapping method",
    ),
}


IMPLEMENTATION_STATUS = {
    **{
        metric_id: "observation_contract_ready"
        for metric_id in (
            "T01",
            "T02",
            "T03",
            "T04",
            "T06",
            "T09",
            "T10",
            "T12",
            "T14",
            "C01",
            "C02",
            "C03",
            "C04",
            "C15",
            "C16",
            "E03",
            "E04",
            "E06",
            "E13",
            "E14",
        )
    },
    "S01": "selected_next_source",
    "S03": "selected_next_source",
    "I01": "primitive_ready_observation_pending",
    "I05": "primitive_ready_observation_pending",
    "I06": "primitive_ready_observation_pending",
    "I10": "primitive_ready_observation_pending",
    "I12": "primitive_ready_observation_pending",
    "I13": "selected_next_source",
    "C09": "source_available_cache_change_needed",
    "C10": "source_available_cache_change_needed",
    "C11": "source_available_cache_change_needed",
}


DATA_GAPS = [
    {
        "gap_id": "GAP_ACTION_FY2020",
        "blocks": ["T05"],
        "need": "FY2020 action records in the evidence-bound transaction cache",
        "reason": "FY2020 exists in the lake and gold view, but the current serving cache deliberately begins in FY2021. An exact five-year CAGR ending FY2025 therefore cannot yet be evidenced from the frozen cache.",
        "gap_type": "serving_cache",
        "source_status": "available_in_lake",
    },
    {
        "gap_id": "GAP_PARENT_LINEAGE",
        "blocks": ["parent-level C01-C16", "E15"],
        "need": "ultimate parent ID/name, resolution method, mapping version and confidence on each action",
        "reason": "Company names cannot safely substitute for a versioned parent relationship.",
        "gap_type": "lineage_and_serving_cache",
        "source_status": "parent_identity_available_in_gold",
    },
    {
        "gap_id": "GAP_COMPETITION_CACHE",
        "blocks": ["C09", "C10", "C11"],
        "need": "competition classification and offers fields retained in the action cache",
        "reason": "The fields exist in the gold view but are absent from transactions.parquet.",
        "gap_type": "serving_cache",
        "source_status": "available_in_gold",
    },
    {
        "gap_id": "GAP_CEILING_LINEAGE",
        "blocks": ["C14"],
        "need": "authoritative current/potential ceiling value with revision identity",
        "reason": "A latest arbitrary ceiling cannot support a trusted utilization metric.",
    },
    {
        "gap_id": "GAP_OPPORTUNITY_HISTORY",
        "blocks": ["L09", "L10", "L11"],
        "need": "published/updated timestamps, change history and validated solicitation-to-award linkage",
        "reason": "Current records support open counts and deadlines, not velocity or historical fit.",
    },
    {
        "gap_id": "GAP_DLA_COMPARABLE_PRICE",
        "blocks": ["I02", "I03", "I04"],
        "need": "quantity, unit price, unit of issue and DLA line key in one evidence-bound cache",
        "reason": "The DLA source contains these line fields, but the general action cache retains only extended value. Aggregate price fields cannot establish comparable unit-price movement.",
        "gap_type": "dedicated_evidence_cache",
        "source_status": "available_in_silver_and_s3",
    },
    {
        "gap_id": "GAP_REFERENCE_SNAPSHOT",
        "blocks": ["I07", "I08", "I09", "I11"],
        "need": "effective-dated FLIS authorized-source snapshots bound to the release manifest",
        "reason": "A current relationship file alone cannot measure source entry, exit or historical status.",
    },
    {
        "gap_id": "GAP_BUDGET_FACTS",
        "blocks": ["B01-B10"],
        "need": "structured, versioned budget and FYDP exhibit facts with page/table/line evidence",
        "reason": "Historical obligations are not a substitute for requested or enacted forward funding.",
        "gap_type": "new_source",
        "source_status": "not_ingested",
    },
    {
        "gap_id": "GAP_PRIMARY_EVENTS",
        "blocks": ["V01-V10"],
        "need": "normalized primary-source events and claim spans with source URLs and versions",
        "reason": "News-like inferences cannot be promoted as metrics without stable event facts.",
        "gap_type": "new_source",
        "source_status": "not_ingested",
    },
    {
        "gap_id": "GAP_COMPANY_FINANCIALS",
        "blocks": ["F01-F06"],
        "need": "SEC and investor-relations revenue, backlog and bookings facts",
        "reason": "Observed procurement value must not be relabelled as company revenue or backlog.",
        "gap_type": "deferred_new_source",
        "source_status": "not_ingested",
    },
]


def registry_rows(metric_ids: Iterable[str] | None = None) -> List[dict]:
    selected = list(metric_ids) if metric_ids is not None else sorted(METRICS)
    rows = []
    for metric_id in selected:
        row = asdict(METRICS[metric_id])
        row["implementation_status"] = IMPLEMENTATION_STATUS[metric_id]
        rows.append(row)
    return rows


def data_gap_rows() -> List[dict]:
    return [dict(gap) for gap in DATA_GAPS]
